@startuml
left to right direction

rectangle "Unsere Webseite" as WebseiteSystem {
  usecase Vorschlaege as "Produktvorschläge erhalten"
  usecase Trainingsplaene as "Trainingspläne generieren"
  usecase Ernaehrungsplaene as "Ernährungspläne generieren"
}

actor Kunde as "👤 Kunde"
actor Webseite as "🌐 Webseite"

 Kunde --> Vorschlaege
 Kunde --> Trainingsplaene
 Kunde --> Ernaehrungsplaene

Vorschlaege --> Webseite
 Webseite <-- Trainingsplaene
 Webseite <-- Ernaehrungsplaene


note top of WebseiteSystem
Kunde fragt an(Pläne, Produktvorschläge),
Webseite generiert per API passende Pläne oder Produkte.

end note
@enduml





